### ISSUE TITLE
Makes a redundant folder

### ISSUE THREAD

**Issue by madsonic** [cs2103t/collate#30]
![screen shot 2015-11-03 at 11 07 51 pm](https://cloud.githubusercontent.com/assets/437672/10911444/d22c252a-827f-11e5-895e-8edbb6b2ab0c.jpg)

'collate from Procrastinate' was entered. 

The md file was not placed inside the newly created folder 'Procrastinate\collated'

**Comment by madsonic** [comment]
This is a bug on mac due to the \ used.

**Comment by sebastianquek** [comment]
@madsonic Thank you!
