### ISSUE TITLE
Tests do not work if the directory of the source files have whitespaces

### ISSUE THREAD

**Issue by sebastianquek** [cs2103t/collate#32]
If you clone the repo to a directory where the full path has whitespaces, the tests will fail.

**Comment by whipermr5** [comment]
Tests also fail on any non-Windows platform or any Windows platform that does not have the paths specified in TestCommandParserAndCommand.java (e.g. system drive not C:, system folders not in standard locations etc.)

**Comment by sebastianquek** [comment]
@whipermr5 You're right. We will need to generalise those tests, but that's another issue altogether.
