### ISSUE TITLE
Add a high-level sequence diagram

### ISSUE THREAD

**Issue by damithc** [cs2103t/collate#36]
It would be good to have an architecture level sequence diagram to show behavior at a higher level

**Comment by damithc** [comment]
Can do this one soon?

**Comment by sebastianquek** [comment]
As the architecture consists of 2 main components, `Backend` & `Data`, and most of the behaviour is contained within `Backend`, how should this sequence diagram be like? How should it differ from the following sequence diagram? 
![sequence-diagram-collate-command](https://cloud.githubusercontent.com/assets/577802/12263237/6b3ed04a-b968-11e5-872d-48ba7e7ac810.png)

**Comment by damithc** [comment]
Based on the current architecture diagram, we have components: `GUI, TUI, Backend, Data, TestDriver`. So the high-level ~~architecture diagram~~ SD should contain only those components. For example, a diagram showing an interaction between `TUI, Backend, Data`.

In the SD we have now, remove the `GUI` component so that it becomes an SD internal to the `Backend` component. i.e. remove the caller (GUI), but keep the call. It doesn't matter who calls the method, the behavior of the component remains the same.

**Comment by damithc** [comment]
To add, the high-level SD probably won't include the `Data` component because it is just a utility component. So we end up with an SD that has just two components. It looks a bit odd, but still, that's the only way we can show SDs at two levels.
